# Generated by Django 2.0.5 on 2018-06-04 13:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='博客类',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('标题方法', models.CharField(max_length=50)),
                ('内容方法', ckeditor_uploader.fields.RichTextUploadingField()),
                ('创建时间方法', models.DateTimeField(auto_now_add=True)),
                ('修改时间方法', models.DateTimeField(auto_now=True)),
                ('作者方法', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-创建时间方法'],
            },
        ),
        migrations.CreateModel(
            name='博客类型类',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('类型名称方法', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='博客类',
            name='类型方法',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='博客应用.博客类型类'),
        ),
    ]
