# Generated by Django 2.0.6 on 2018-06-25 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('博客应用', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='博客类',
            name='作者方法',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='博客类',
            name='类型方法',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='博客应用.博客类型类'),
        ),
    ]
