# Generated by Django 2.0.6 on 2018-06-18 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('评论功能', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='评论类',
            options={'ordering': ['-评论时间方法']},
        ),
        migrations.AddField(
            model_name='评论类',
            name='回复哪个用户方法',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='回复人', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='评论类',
            name='回复哪条评论方法',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='评论功能.评论类'),
        ),
        migrations.AlterField(
            model_name='评论类',
            name='评论人方法',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='评论人', to=settings.AUTH_USER_MODEL),
        ),
    ]
