# Generated by Django 2.0.6 on 2018-06-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('评论功能', '0004_auto_20180620_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='评论类',
            options={'ordering': ['评论时间方法']},
        ),
    ]
