# Generated by Django 2.0.5 on 2018-06-04 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('阅读统计', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='计数信息类',
            name='日期信息方法',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
