# Generated by Django 2.0.6 on 2018-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('个人网站项目', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='简介类',
            name='昵称方法',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
    ]
